apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-app-deployment
  labels:
    app: go-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-sample-app
  template:
    metadata:
      labels:
        app: go-sample-app
    spec:
      containers:
      - name: go-sample-app
        image: us-central1-docker.pkg.dev/gke-demo1-437208/gke-repo/go-sample-app
        ports:
        - containerPort: 8080
        env:
        - name: GIN_MODE
          value: "release"
        - name: MONGO_URI
          value: "mongodb://admin:password@mongodb-service:27017"
        - name: REDIS_ADDRESS
          value: "redis-service:6379"