apiVersion: v1
kind: Service
metadata:
  name: go-sample-app-service
spec:
  selector:
    app: go-sample-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
